---
- hosts: virt-host
  vars_files:
    - vars/virt_host.yml
    - vars/network.yml
  tasks: []
  roles:
    - { role: virt-host }
    # will need to create vars file for bridge names and IP ranges

    # check for bridge network (libvirt)

    # configure the bridge network (libvirt)

    # instantiate the vm with the virt commands

    # add virtual machine to inventory (undercloud)

- hosts: undercloud
  vars_files:
    - vars/instack.yml
    - vars/undercloud.yml
    - vars/network.yml
    - vars/undercloud_vlans.yml
  tasks:
    - command: echo foo

  # roles:
  #   # - { role: undercloud }
  #   # - { role: build_images }
  #   # - { role: instackenv }
  #   # - { role: dns }
  #   # - { role: undercloud-vlans }
  #   - { role: heat-templates }
  #   # - { role: overcloud_deploy }
