---
# http://buildlogs.centos.org/centos/7/cloud/x86_64/tripleo_images/mitaka/delorean/
# http://buildlogs.centos.org/centos/7/cloud/x86_64/tripleo_images/liberty/delorean/

# - name: Ensure file for images exists

- name: Validate images directory exists
  become: yes
  become_user: stack
  file:
    path: /home/stack/images
    state: directory

- name: Check if images exist
  become: yes
  become_user: stack
  stat:
    path: /home/stack/images/{{ item }}
  with_items: "{{ tripleo_images }}"
  register: image_files

- name: Get the images
  become: yes
  become_user: stack
  get_url:
    url: "{{ tripleo_image_path}}/{{ item.item }}"
    dest: "{{ item.invocation.module_args.path }}"
  with_items: "{{ image_files.results }}"
  when: not item.stat.exists
