---

# ------------------------------------------------------------------------------------------------------
# For your reference...
# http://docs.openstack.org/developer/tripleo-docs/basic_deployment/basic_deployment_cli.html
#
# ------------------------------------------------------------------------------------------------------

- name: Set hostname
  hostname: 
    name: "{{ undercloud_hostname }}"

- name: Install packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items: 
    - yum-utils
    - tcpdump
    - libselinux-python
    - libguestfs-tools
    # - python-pip

- name: Create stack user
  user: 
    name: stack 
    comment: "infamous openstack stack user"

- name: set sudoers.d file
  copy: 
    src: sudoers.stack
    dest: /etc/sudoers.d/stack
    mode: 0444

# ---------------------------- STABLE REPOS.

- name:  Enable latest RDO Delorean repository for all packages for specific version
  get_url: 
    url: "https://trunk.rdoproject.org/centos7-{{ openstack_named_version }}/current/delorean.repo"
    dest: "/etc/yum.repos.d/delorean-{{ openstack_named_version }}.repo"

- name: Enable the Delorean Deps repository
  get_url:
    url: "http://trunk.rdoproject.org/centos7-{{ openstack_named_version }}/delorean-deps.repo"
    dest: "/etc/yum.repos.d/delorean-deps-{{ openstack_named_version }}.repo"

- name: Install the yum-plugin-priorities package 
  yum: 
    name: yum-plugin-priorities
    state: present

- name: "Install the TripleO CLI (this pulls other deps, as you would imagine)"
  yum: 
    name: python-tripleoclient
    state: present

- name: Template undercloud.conf
  template:
    src: "{{ openstack_named_version }}.undercloud.conf.j2"
    dest: "/home/stack/undercloud.conf"

- name: Install undercloud
  command: openstack undercloud install
  args:
    creates: /home/stack/.undercloud_installed
  become: true
  become_user: stack

- name: Mark undercloud install complete
  file: 
    path: /home/stack/.undercloud_installed 
    state: directory
  become: true
  become_user: stack
